# Generated by Django 5.0.6 on 2024-05-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='picture_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
